"use client";
import { useMemo, useState } from "react";

const defaults = { price: 325000, down: 25, rate: 6.75, term: 30, rent: 2700, tax: 3600, hoa: 180, vacancy: 6, reserves: 5, maintenance: 5, management: 8, years: 10, appreciation: 3, income: 140000, marginal: 24 };
const money = (n:number) => new Intl.NumberFormat("en-US", { style:"currency", currency:"USD", maximumFractionDigits:0 }).format(n);
const pct = (n:number) => `${n.toFixed(1)}%`;

export default function Home() {
  const [v,setV] = useState(defaults);
  const set = (k:keyof typeof defaults, x:string) => setV(s => ({...s,[k]:Number(x)}));
  const c = useMemo(() => {
    const loan=v.price*(1-v.down/100), r=v.rate/1200, n=v.term*12;
    const payment=r ? loan*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1) : loan/n;
    let balance=loan, interest=0, principal=0;
    for(let i=0;i<12;i++){const mi=balance*r, mp=payment-mi; interest+=mi; principal+=mp; balance-=mp;}
    const rent=v.rent, vacancy=rent*v.vacancy/100, management=rent*v.management/100, tax=v.tax/12, hoa=v.hoa, reserves=rent*v.reserves/100, maintenance=rent*v.maintenance/100;
    const noi=(rent-vacancy)*12-v.tax-v.hoa*12-(reserves+maintenance)*12, debt=payment*12, cashFlow=noi-debt-management*12;
    const cashIn=v.price*v.down/100+v.price*.025, cap=noi/v.price*100, coc=cashFlow/cashIn*100, dscr=noi/debt;
    const depreciation=v.price*.75/27.5, taxableBeforeDep=(rent*12-vacancy*12-v.tax-v.hoa*12-(reserves+maintenance)*12-management*12)-interest;
    const paperLoss=Math.max(0,depreciation-taxableBeforeDep), repsTaxBenefit=(interest+depreciation)*v.marginal/100, nonRepsBenefit=0;
    const future=v.price*Math.pow(1+v.appreciation/100,v.years), futureBalance=loan*Math.pow(1+r,v.years*12)-payment*((Math.pow(1+r,v.years*12)-1)/r);
    const equity=future-futureBalance, totalReturn=(equity-cashIn+cashFlow*v.years+repsTaxBenefit*v.years)/cashIn*100;
    return {loan,payment,interest,principal,rent,vacancy,management,tax,hoa,reserves,maintenance,noi,debt,cashFlow,cashIn,cap,coc,dscr,depreciation,taxableBeforeDep,paperLoss,repsTaxBenefit,nonRepsBenefit,equity,totalReturn};
  },[v]);
  const verdict=c.coc>=6&&c.dscr>=1.2&&c.cap>=5.5?"Strong candidate":c.coc>=3?"Needs negotiation":"Pass for now";
  return <main><nav><div className="brand"><span>◒</span> EstateIQ</div><div className="navlinks"><a href="#analyze">Analyze</a><a href="#taxes">Tax view</a><button className="ghost" onClick={()=>setV(defaults)}>Reset model</button></div></nav>
  <section className="hero"><div><div className="eyebrow">REAL ESTATE UNDERWRITING, SIMPLIFIED</div><h1>Know the deal<br/><em>before</em> you buy.</h1><p>Model cash flow, debt paydown, tax impact and long-term returns from one transparent investment case.</p><a className="primary" href="#analyze">Start analyzing <span>↗</span></a></div><div className="hero-card"><div className="card-label">LIVE MODEL PREVIEW</div><div className="mini-title">{v.years}-year projected return</div><div className="big-number">{pct(c.totalReturn)}</div><div className="up">↑ Based on your assumptions</div><div className="mini-row"><span>Cash-on-cash <b>{pct(c.coc)}</b></span><span>DSCR <b>{c.dscr.toFixed(2)}x</b></span></div></div></section>
  <section id="analyze" className="workspace"><div className="section-head"><div><div className="eyebrow">THE UNDERWRITER</div><h2>Build your investment case.</h2></div><div className="saved">● Model auto-saved locally</div></div><div className="grid"><div className="panel inputs"><h3>Property & financing</h3><p className="muted">Tune any assumption. Results update instantly.</p><div className="fields"><Field label="Property price" value={v.price} k="price" prefix="$" set={set}/><Field label="Down payment" value={v.down} k="down" suffix="%" set={set}/><Field label="Mortgage rate" value={v.rate} k="rate" suffix="%" set={set}/><Field label="Loan term" value={v.term} k="term" suffix="yrs" set={set}/><Field label="Monthly rent" value={v.rent} k="rent" prefix="$" set={set}/><Field label="Property tax / year" value={v.tax} k="tax" prefix="$" set={set}/><Field label="HOA / month" value={v.hoa} k="hoa" prefix="$" set={set}/><Field label="Vacancy" value={v.vacancy} k="vacancy" suffix="%" set={set}/></div><div className="subhead">Operating & tax assumptions</div><div className="fields"><Field label="Cap reserves" value={v.reserves} k="reserves" suffix="% of rent" set={set}/><Field label="Maintenance" value={v.maintenance} k="maintenance" suffix="% of rent" set={set}/><Field label="Management fee" value={v.management} k="management" suffix="%" set={set}/><Field label="Hold period" value={v.years} k="years" suffix="yrs" set={set}/><Field label="Annual income" value={v.income} k="income" prefix="$" set={set}/><Field label="Marginal tax rate" value={v.marginal} k="marginal" suffix="%" set={set}/></div></div>
  <div className="panel results"><div className="result-top"><div><h3>Investment snapshot</h3><p className="muted">Your screen for the deal.</p></div><span className={verdict.includes("Strong")?"pill good":"pill warn"}>{verdict}</span></div><div className="metrics"><Metric label="Cap rate" value={pct(c.cap)} hint="Target 5–6%+"/><Metric label="Cash-on-cash" value={pct(c.coc)} hint="Target 6–8%+"/><Metric label="DSCR" value={`${c.dscr.toFixed(2)}x`} hint="Target 1.20x+"/></div><div className="cashflow"><h4>Monthly cash-flow waterfall</h4><Line label="Gross rent" value={c.rent}/><Line label="Less: vacancy" value={-c.vacancy}/><Line label="Less: property tax" value={-c.tax}/><Line label="Less: HOA" value={-c.hoa}/><Line label="Less: reserves" value={-c.reserves}/><Line label="Less: maintenance" value={-c.maintenance}/><Line label="Less: management" value={-c.management}/><Line label="NOI before debt" value={c.noi/12} strong/><Line label="Less: mortgage P&I" value={-c.payment}/><Line label="Monthly cash flow" value={c.cashFlow/12} strong final/></div><div className="projection"><div className="projection-head"><span>Equity projection</span><b>{money(c.equity)}</b></div><div className="bar"><span style={{width:`${Math.min(100,Math.max(10,c.totalReturn/2))}%`}}/></div><div className="axis"><span>Today</span><span>{v.years} years</span></div></div></div></div></section>
  <section id="taxes" className="tax-section"><div className="eyebrow">TAX IMPACT EXPLAINED</div><h2>Separate cash economics from tax economics.</h2><p className="muted wide">Mortgage interest and depreciation can reduce taxable income; principal is not deductible, but it builds equity. The estimates below are simplified and should be reviewed with a tax professional.</p><div className="tax-grid"><div className="panel"><h3>Year-one tax building blocks</h3><Line label="Mortgage interest" value={-c.interest}/><Line label="Mortgage principal" value={c.principal} note="Not a tax deduction; increases equity"/><Line label="Estimated depreciation" value={-c.depreciation}/><Line label="Estimated taxable rental result" value={c.taxableBeforeDep-c.depreciation} strong/><div className="tax-note">Paper loss modeled: <b>{money(c.paperLoss)}</b></div></div><div className="panel"><h3>Estimated tax benefit by scenario</h3><div className="scenario"><div><span>With REPS</span><small>Modeled ordinary-income benefit from interest + depreciation</small></div><b className="positive">{money(c.repsTaxBenefit)}/yr</b></div><div className="scenario"><div><span>Without REPS</span><small>Conservative model assumes passive loss cannot offset salary</small></div><b>{money(c.nonRepsBenefit)}/yr</b></div><div className="tax-note">REPS = Real Estate Professional Status. Actual rules depend on participation, passive-loss limits, income, filing status, and other activities.</div></div></div></section>
  <section className="guide"><div className="eyebrow">READ THE SIGNALS</div><h2>Three numbers to keep you honest.</h2><div className="guide-grid"><article><div className="icon">◉</div><h3>Cap Rate <small>Your screen</small></h3><p>NOI divided by property price. Use it to screen out overpriced deals.</p></article><article><div className="icon">↗</div><h3>Cash-on-Cash <small>Your pocket</small></h3><p>Annual cash flow divided by total cash invested after debt service.</p></article><article><div className="icon">▣</div><h3>DSCR <small>The bank’s view</small></h3><p>NOI divided by annual mortgage payment. Banks commonly look for 1.20x or better.</p></article></div></section><footer><div className="brand"><span>◒</span> EstateIQ</div><p>Educational analysis only. Validate assumptions with a qualified tax and financial professional.</p></footer></main>;
}
function Field({label,value,k,prefix,suffix,set}:{label:string,value:number,k:keyof typeof defaults,prefix?:string,suffix?:string,set:(k:keyof typeof defaults,v:string)=>void}){return <label className="field"><span>{label}</span><div>{prefix&&<i>{prefix}</i>}<input type="number" value={value} onChange={e=>set(k,e.target.value)}/>{suffix&&<i>{suffix}</i>}</div></label>}
function Line({label,value,strong,final,note}:{label:string,value:number,strong?:boolean,final?:boolean,note?:string}){return <div className={`line ${strong?"strong":""} ${final?"final":""}`}><span>{label}{note&&<small>{note}</small>}</span><b>{money(value)}</b></div>}
function Metric({label,value,hint}:{label:string,value:string,hint:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>}
